# Generated by Django 3.0.4 on 2020-03-08 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trainings_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='training_time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(verbose_name='training_date'),
        ),
    ]
